# This workflow fires off of pushes to master branch. If the head commit message contains '[ci skip]', the whole workflow will be skipped.
#
# Secrets used:
# AZURE_APP_SERVICE_PUBLISH_PROFILE credentials to authenticate with Azure: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials

name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Project
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build project
        run: |
          cd ./MoneyManagerService
          dotnet publish -c=Release
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: money-manager-service-b${{ github.run_number }}
          path: ./MoneyManagerService/bin/Release/netcoreapp5.0

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "rherber-money-manager-service"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          package: money-manager-service-b${{ github.run_number }}
